[General]
# Основные настройки
PROTO_MARK = blackhole
OUTPUT_FILE = 

# Имена файлов (относительно директории скрипта)
WHITELIST_FILENAME = whitelist.txt
BLACKLIST_FILENAME = blacklist.txt

[Sources]
# Ссылки на внешние blacklist'ы
URLS = 
    https://raw.githubusercontent.com/C24Be/AS_Network_List/refs/heads/main/blacklists/blacklist-v4.txt
    https://raw.githubusercontent.com/C24Be/AS_Network_List/refs/heads/main/blacklists/blacklist-v6.txt
    https://raw.githubusercontent.com/tread-lightly/CyberOK_Skipa_ips/refs/heads/main/lists/skipa_cidr.txt